name = "my-wallet"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "wallet-db"
database_id = "d9451a5c-0f3e-48af-91ca-515adefdbf0e"
migrations_dir = "prisma/migrations"